[project]
name = "scripts"
version = "0.1.0"
description = "Apple Security Advisory Scraper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp",
    "beautifulsoup4",
    "markdownify",
    "requests"
]
